spring:
    application:
        name: pitterpatter
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/pitterpatter?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
        username: shell_script_will_replace_this_db_username
        password: shell_script_will_replace_this_db_password

    redis:
        host: redis
        port: 6379

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: shell_script_will_replace_this_kakao_client_id
                        client-secret: shell_script_will_replace_this_kakao_client_secret
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        client-authentication-method: post
                        client-name: kakao
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize 
                        token-uri: https://kauth.kakao.com/oauth/token 
                        user-info-uri: https://kapi.kakao.com/v2/user/me 
                        user-name-attribute: id 

    devtools:
        livereload:
            enabled: true
        remote:
            restart:
                enabled: true

    mail:
        host: shell_script_will_replace_this_email_host
        port: shell_script_will_replace_this_email_port
        username: shell_script_will_replace_this_email
        password: shell_script_will_replace_this_email_password
        properties:
            mail:
                smtp:
                    auth: shell_script_will_replace_this_email_auth
                    starttls:
                        enable: shell_script_will_replace_this_email_starttls_enable
                        required: shell_script_will_replace_this_email_starttls_required

jasypt:
    encryptor:
        bean: stringEncryptor

logging:
    level:
        com.pitpat: DEBUG

jwt:
    header: Authorization
    secret: shell_script_will_replace_this_jwt_secret

custom:
    random-2fa: shell_script_will_replace_this_random_2fa

